"""Integration tests for charter runtime behavior.

Tests the charter system's runtime behavior including:
- Charter discovery in main repo and package
- Loading and validation
- Graceful fallback when missing
- Migration creates valid files
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

pytestmark = pytest.mark.git_repo


class TestCharterDiscovery:
    """Tests for charter file discovery."""

    def test_discover_charter_in_main_repo(self, tmp_path: Path):
        """Test discovering charter file in main repository."""
        # Create main repo with charter
        repo = tmp_path / "repo"
        repo.mkdir()

        # Initialize git
        subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True)
        subprocess.run(
            ["git", "config", "user.name", "Test"],
            cwd=repo,
            check=True,
            capture_output=True,
        )
        subprocess.run(
            ["git", "config", "user.email", "test@example.com"],
            cwd=repo,
            check=True,
            capture_output=True,
        )

        # Create .kittify structure
        kittify_dir = repo / ".kittify"
        memory_dir = kittify_dir / "memory"
        memory_dir.mkdir(parents=True)

        # Create charter file
        charter_file = memory_dir / "charter.md"
        charter_content = """# Project Charter

> Auto-generated by spec-kitty charter command
> Created: 2026-01-23
> Version: 1.0.0

## Purpose

This charter captures the technical standards for the project.

## Technical Standards

### Languages and Frameworks
Python 3.11+ with pytest for testing

### Testing Requirements
pytest with 80% line coverage required

### Performance and Scale
CLI operations should complete in < 2 seconds

### Deployment and Constraints
Cross-platform: Linux, macOS, Windows 10+

## Governance

### Amendment Process
Any team member can propose amendments via pull request.

### Compliance Validation
Code reviewers validate compliance during PR review.
"""
        charter_file.write_text(charter_content, encoding="utf-8")

        # Verify file exists and can be read
        assert charter_file.exists()
        content = charter_file.read_text(encoding="utf-8")
        assert "Project Charter" in content
        assert "Technical Standards" in content
        assert "Python 3.11+" in content

    def test_discover_charter_in_package(self, tmp_path: Path):
        """Test discovering charter template in package resources."""
        # Create package-like structure
        package_dir = tmp_path / "package"
        package_dir.mkdir()

        # Simulate package structure
        templates_dir = package_dir / "templates" / "command-templates"
        templates_dir.mkdir(parents=True)

        # Charter command template should exist
        charter_template = templates_dir / "charter.md"
        charter_template.write_text(
            """---
description: Create or update the project charter
---

## What This Command Does

This command creates or updates the project charter.
""",
            encoding="utf-8",
        )

        # Verify template exists
        assert charter_template.exists()
        content = charter_template.read_text(encoding="utf-8")
        assert "project charter" in content.lower()

    def test_charter_loads_correctly(self, tmp_path: Path):
        """Test that charter file loads with correct structure."""
        # Create charter
        memory_dir = tmp_path / ".kittify" / "memory"
        memory_dir.mkdir(parents=True)

        charter_file = memory_dir / "charter.md"
        charter_content = """# Test Project Charter

> Version: 1.0.0

## Technical Standards

### Languages and Frameworks
TypeScript 4.9+ with React 18

### Testing Requirements
Jest with 90% coverage

## Governance

### Amendment Process
Standard PR process
"""
        charter_file.write_text(charter_content, encoding="utf-8")

        # Load and validate structure
        content = charter_file.read_text(encoding="utf-8")

        # Verify required sections
        assert "# Test Project Charter" in content
        assert "## Technical Standards" in content
        assert "### Languages and Frameworks" in content
        assert "### Testing Requirements" in content
        assert "## Governance" in content
        assert "### Amendment Process" in content

        # Verify content
        assert "TypeScript 4.9+" in content
        assert "Jest with 90% coverage" in content

    def test_charter_validation_passes(self, tmp_path: Path):
        """Test that valid charter passes validation checks."""
        memory_dir = tmp_path / ".kittify" / "memory"
        memory_dir.mkdir(parents=True)

        charter_file = memory_dir / "charter.md"
        charter_content = """# Valid Charter

> Version: 1.0.0

## Technical Standards

### Languages and Frameworks
Rust 1.70+ with no external dependencies

### Testing Requirements
cargo test, all features must have tests

### Performance and Scale
Handle 1000 requests/second at p95 < 200ms

### Deployment and Constraints
Docker-only, deployed to Kubernetes

## Code Quality

### Pull Request Requirements
2 approvals required, 1 must be from core team

### Quality Gates
All tests pass, coverage ≥80%, linter clean

## Governance

### Amendment Process
PR with 2 approvals, announce in team chat

### Compliance Validation
Code reviewers check compliance
"""
        charter_file.write_text(charter_content, encoding="utf-8")

        # Validate structure
        content = charter_file.read_text(encoding="utf-8")

        # Check all required sections present
        required_sections = [
            "# Valid Charter",
            "## Technical Standards",
            "### Languages and Frameworks",
            "### Testing Requirements",
            "### Performance and Scale",
            "### Deployment and Constraints",
            "## Governance",
            "### Amendment Process",
            "### Compliance Validation",
        ]

        for section in required_sections:
            assert section in content, f"Missing required section: {section}"


class TestCharterGracefulFallback:
    """Tests for graceful fallback when charter is missing."""

    def test_runs_without_charter(self, tmp_path: Path):
        """Test that spec-kitty commands run without charter file."""
        # Create minimal project structure (no charter)
        kittify_dir = tmp_path / ".kittify"
        kittify_dir.mkdir()

        memory_dir = kittify_dir / "memory"
        memory_dir.mkdir()

        # No charter.md file

        # Verify directory structure works without charter
        assert kittify_dir.exists()
        assert memory_dir.exists()
        assert not (memory_dir / "charter.md").exists()

        # Create a minimal config file
        config_file = kittify_dir / "config.yaml"
        config_file.write_text("version: '0.12.0'\n", encoding="utf-8")

        assert config_file.exists()

    def test_warns_when_charter_missing(self, tmp_path: Path):
        """Test that missing charter is handled gracefully (no errors)."""
        memory_dir = tmp_path / ".kittify" / "memory"
        memory_dir.mkdir(parents=True)

        # No charter file
        charter_path = memory_dir / "charter.md"

        # Check file doesn't exist
        assert not charter_path.exists()

        # This should not raise an error - commands should work without it
        # (In real code, commands check if file exists before reading)
        content = charter_path.read_text(encoding="utf-8") if charter_path.exists() else None

        assert content is None

    def test_uses_default_templates_without_charter(self, tmp_path: Path):
        """Test that default templates are used when charter is missing."""
        # Create project without charter
        kittify_dir = tmp_path / ".kittify"
        templates_dir = kittify_dir / "templates"
        templates_dir.mkdir(parents=True)

        # Create a basic template (plan template references charter optionally)
        plan_template = templates_dir / "plan-template.md"
        plan_template_content = """# Implementation Plan

Load context: Read FEATURE_SPEC and `.kittify/charter/charter.md` if it exists.
If the charter file is missing, skip Charter Check and note that it is absent.

## Plan Structure

... rest of template ...
"""
        plan_template.write_text(plan_template_content, encoding="utf-8")

        # Verify template exists
        assert plan_template.exists()
        content = plan_template.read_text(encoding="utf-8")
        assert "if it exists" in content
        assert "If the charter file is missing" in content

    def test_charter_migration_creates_valid_files(self, tmp_path: Path):
        """Test that migration/init creates valid charter files."""
        # Simulate charter creation during init
        memory_dir = tmp_path / ".kittify" / "memory"
        memory_dir.mkdir(parents=True)

        # Create minimal placeholder (skip scenario)
        charter_file = memory_dir / "charter.md"
        placeholder_content = """# Project Charter

Charter skipped - not required for spec-kitty usage.

Run `/spec-kitty.charter` anytime to create a full charter.
"""
        charter_file.write_text(placeholder_content, encoding="utf-8")

        # Verify placeholder is valid
        assert charter_file.exists()
        content = charter_file.read_text(encoding="utf-8")
        assert "Charter skipped" in content
        assert "/spec-kitty.charter" in content

    def test_charter_minimal_creation(self, tmp_path: Path):
        """Test creating minimal charter with Phase 1 only."""
        memory_dir = tmp_path / ".kittify" / "memory"
        memory_dir.mkdir(parents=True)

        charter_file = memory_dir / "charter.md"
        minimal_content = """# My Project Charter

> Auto-generated by spec-kitty charter command
> Created: 2026-01-23
> Version: 1.0.0

## Purpose

This charter captures the technical standards for My Project.

## Technical Standards

### Languages and Frameworks
Python 3.11+ with FastAPI for backend

### Testing Requirements
pytest with 80% line coverage, 100% for critical paths

### Performance and Scale
Handle 1000 requests/second at p95 < 200ms

### Deployment and Constraints
Docker-only, deployed to Kubernetes

## Governance

### Amendment Process
Any team member can propose amendments via pull request. Changes are discussed
and merged following standard PR review process.

### Compliance Validation
Code reviewers validate compliance during PR review. Charter violations
should be flagged and addressed before merge.

### Exception Handling
Exceptions discussed case-by-case with team. Strong justification required.
Consider updating charter if exceptions become common.
"""
        charter_file.write_text(minimal_content, encoding="utf-8")

        # Verify minimal charter is valid
        content = charter_file.read_text(encoding="utf-8")
        assert "## Technical Standards" in content
        assert "## Governance" in content
        # Should not have optional sections
        assert "## Code Quality" not in content
        assert "## Tribal Knowledge" not in content

    def test_charter_comprehensive_creation(self, tmp_path: Path):
        """Test creating comprehensive charter with all phases."""
        memory_dir = tmp_path / ".kittify" / "memory"
        memory_dir.mkdir(parents=True)

        charter_file = memory_dir / "charter.md"
        comprehensive_content = """# Enterprise Project Charter

> Auto-generated by spec-kitty charter command
> Created: 2026-01-23
> Version: 1.0.0

## Purpose

This charter captures the technical standards, code quality expectations,
tribal knowledge, and governance rules for Enterprise Project.

## Technical Standards

### Languages and Frameworks
Java 17+ with Spring Boot 3.0

### Testing Requirements
JUnit 5 with 85% coverage, integration tests required

### Performance and Scale
Support 10k concurrent users, 1M daily active users

### Deployment and Constraints
Kubernetes on AWS EKS, multi-region deployment

## Code Quality

### Pull Request Requirements
2 approvals required, 1 must be from core team

### Code Review Checklist
Tests added, documentation updated, security scan clean, no performance regressions

### Quality Gates
All tests pass, coverage ≥85%, SonarQube quality gate passed, security scan clean

### Documentation Standards
All public APIs must have Javadoc + examples, ADRs for architectural decisions

## Tribal Knowledge

### Team Conventions
Use Optional<T> for nullable values, never return null from public APIs

### Lessons Learned
Always version APIs from day 1, write integration tests first

### Historical Decisions
Chose microservices for independent scaling, chose Kafka for event streaming

## Governance

### Amendment Process
PR with 2 approvals, announce in team chat, 1 week discussion period

### Compliance Validation
Code reviewers check compliance, architecture review board validates architectural decisions

### Exception Handling
Document in ADR, require 3 approvals, set sunset date for temporary exceptions
"""
        charter_file.write_text(comprehensive_content, encoding="utf-8")

        # Verify comprehensive charter has all sections
        content = charter_file.read_text(encoding="utf-8")
        assert "## Technical Standards" in content
        assert "## Code Quality" in content
        assert "## Tribal Knowledge" in content
        assert "## Governance" in content

        # Verify all subsections
        assert "### Languages and Frameworks" in content
        assert "### Pull Request Requirements" in content
        assert "### Team Conventions" in content
        assert "### Amendment Process" in content

    def test_charter_accessible_from_worktree(self, tmp_path: Path):
        """Test that charter is accessible from worktree context."""
        # Create main repo with charter
        repo = tmp_path / "repo"
        repo.mkdir()

        subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True)
        subprocess.run(
            ["git", "config", "user.name", "Test"],
            cwd=repo,
            check=True,
            capture_output=True,
        )
        subprocess.run(
            ["git", "config", "user.email", "test@example.com"],
            cwd=repo,
            check=True,
            capture_output=True,
        )

        # Create charter in main repo
        memory_dir = repo / ".kittify" / "memory"
        memory_dir.mkdir(parents=True)

        charter_file = memory_dir / "charter.md"
        charter_file.write_text("# Main Charter\n\nTest content", encoding="utf-8")

        # Create initial commit
        (repo / "README.md").write_text("test")
        subprocess.run(["git", "add", "."], cwd=repo, check=True, capture_output=True)
        subprocess.run(
            ["git", "commit", "-m", "init"],
            cwd=repo,
            check=True,
            capture_output=True,
        )

        # Create worktree
        worktree_dir = repo / ".worktrees" / "feature-lane-a"
        subprocess.run(
            ["git", "worktree", "add", str(worktree_dir), "-b", "kitty/mission-feature-lane-a"],
            cwd=repo,
            check=True,
            capture_output=True,
        )

        # Charter should be accessible from main repo
        # (Worktrees reference main repo's .kittify via relative path)
        assert charter_file.exists()

        # In real usage, commands running in worktree would reference
        # main repo's charter via path resolution
        content = charter_file.read_text(encoding="utf-8")
        assert "Main Charter" in content
