"""Migration: emit Roo Code deprecation notice and remove roo from config.yaml.

Roo Code (the editor) shut down on 2026-05-15.  This migration:

- Emits a Rich deprecation panel when ``.roo/`` is detected on a project
  (C-007: preserve the directory — do NOT delete it).
- Removes ``roo`` from ``.kittify/config.yaml`` when present, so future
  upgrades do not process a retired agent directory.

The migration is idempotent: re-running on a project where ``roo`` was
already removed from ``config.yaml`` is a no-op.
"""

from __future__ import annotations

from pathlib import Path

from ..registry import MigrationRegistry
from .base import BaseMigration, MigrationResult

_ROO_DIR = ".roo"
_ROO_AGENT_KEY = "roo"
_DEPRECATION_DATE = "2026-05-15"


def _has_roo_dir(project_path: Path) -> bool:
    return (project_path / _ROO_DIR).exists()


def _read_config_yaml_raw(project_path: Path) -> list[str]:
    """Return the raw ``agents.available`` list from config.yaml.

    Reads the YAML file directly (bypassing ``load_agent_config``'s
    ``AI_CHOICES`` validation) so that projects with a stale ``roo`` entry
    can still be processed by this migration.
    """
    config_file = project_path / ".kittify" / "config.yaml"
    if not config_file.exists():
        return []
    try:
        from ruamel.yaml import YAML

        yaml = YAML()
        with config_file.open() as fh:
            data = yaml.load(fh) or {}
        agents_data = data.get("agents") or data.get("tools") or {}
        if isinstance(agents_data, dict):
            available = agents_data.get("available", [])
            if isinstance(available, list):
                return [str(a) for a in available]
        return []
    except Exception:  # noqa: BLE001 — config unreadable; treat as empty
        return []


def _roo_in_config(project_path: Path) -> bool:
    """Return True when ``roo`` is listed in ``.kittify/config.yaml``."""
    return _ROO_AGENT_KEY in _read_config_yaml_raw(project_path)


@MigrationRegistry.register
class RooDeprecationMigration(BaseMigration):
    """Emit Roo Code deprecation notice and remove roo from agent config."""

    migration_id = "0_9_4_roo_deprecation"
    description = "Emit Roo Code deprecation notice; remove 'roo' from .kittify/config.yaml"
    target_version = "3.2.0rc44"
    runs_on_worktrees = False

    def detect(self, project_path: Path) -> bool:
        """Return True when .roo/ exists or roo is still in config.yaml."""
        return _has_roo_dir(project_path) or _roo_in_config(project_path)

    def can_apply(self, project_path: Path) -> tuple[bool, str]:  # noqa: ARG002 — no preconditions to check
        """Always safe to apply."""
        return True, ""

    def apply(self, project_path: Path, dry_run: bool = False) -> MigrationResult:
        """Emit deprecation notice and remove roo from config (if present)."""
        changes: list[str] = []
        warnings: list[str] = []

        # --- Emit deprecation notice when .roo/ is present ------------------
        if _has_roo_dir(project_path):
            _emit_deprecation_notice()
            changes.append(f"Roo Code deprecation notice emitted (.roo/ preserved at {project_path / _ROO_DIR})")

        # --- Remove roo from config.yaml ------------------------------------
        if _roo_in_config(project_path):
            if not dry_run:
                removed = _remove_roo_from_config(project_path)
                if removed:
                    changes.append("Removed 'roo' from .kittify/config.yaml (agent no longer supported)")
                else:
                    warnings.append("Could not remove 'roo' from config.yaml; manual cleanup may be required")
            else:
                changes.append("dry-run: would remove 'roo' from .kittify/config.yaml")

        return MigrationResult(
            success=True,
            changes_made=changes,
            warnings=warnings,
        )


def _emit_deprecation_notice() -> None:
    """Print the Roo Code deprecation panel to the console."""
    try:
        from rich.console import Console
        from rich.panel import Panel

        console = Console(stderr=True)
        console.print(
            Panel(
                "[yellow]Roo Code has been discontinued as of " + _DEPRECATION_DATE + ".[/yellow]\n"
                "The [bold].roo/[/bold] directory has been preserved but Roo Code\n"
                "will no longer be maintained or generated by spec-kitty.\n"
                "You may safely delete [bold].roo/[/bold] if you are not using Roo Code.\n\n"
                "Remove the agent from your project config:\n"
                "  [cyan]spec-kitty agent config remove roo[/cyan]",
                title="Roo Code Deprecation Notice",
                border_style="yellow",
            )
        )
    except Exception:  # noqa: BLE001 — notice failure must not block migration
        import logging

        logging.getLogger(__name__).warning(
            "Roo Code has been discontinued (%s). The .roo/ directory is preserved but will no longer be maintained. Run: spec-kitty agent config remove roo",
            _DEPRECATION_DATE,
        )


def _remove_roo_from_config(project_path: Path) -> bool:
    """Remove ``roo`` from ``.kittify/config.yaml``'s agents list.

    Reads and writes the YAML file directly (bypassing ``load_agent_config``
    validation) so that stale ``roo`` entries can be cleaned up even though
    ``roo`` is no longer in ``AI_CHOICES``.

    Returns True when the config was successfully updated, False on error.
    """
    config_file = project_path / ".kittify" / "config.yaml"
    if not config_file.exists():
        return True  # nothing to do

    try:
        from ruamel.yaml import YAML

        yaml = YAML()
        yaml.preserve_quotes = True
        with config_file.open() as fh:
            data = yaml.load(fh) or {}

        agents_data = data.get("agents") or data.get("tools")
        if not isinstance(agents_data, dict):
            return True  # unexpected shape — leave it alone

        available = agents_data.get("available", [])
        if not isinstance(available, list) or _ROO_AGENT_KEY not in available:
            return True  # already absent

        agents_data["available"] = [a for a in available if a != _ROO_AGENT_KEY]

        with config_file.open("w") as fh:
            yaml.dump(data, fh)

        return True
    except Exception:  # noqa: BLE001 — log and report; do not hard-fail migration
        import logging

        logging.getLogger(__name__).warning("Could not remove 'roo' from config.yaml; run: spec-kitty agent config remove roo")
        return False
